version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hub-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://root:rootpassword@mongo:27017/hub?authSource=admin
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: hub

volumes:
  mongo_data:
