service: afya
provider:
  name: aws
  region: us-east-1
  endpoint: http://localstack:4566
  environment:
    MONGO_URI: "mongodb://root:rootpassword@localhost:27017/mongodatabase?authSource=admin"

functions:
  processSalesReport:
    handler: src/lambda.processSalesReport
    events:
      - schedule: rate(24 hours) # Executa a cada 24 horas
